Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.network :forwarded_port, host: 4000, guest: 4000
  config.vm.provision :shell, path: "bootstrap.sh"

  # Proxy config
  # config.proxy.http = ""
  # config.proxy.https = ""
  # config.proxy.no_proxy = "localhost,127.0.0.1"
end